function dC = dC_loop_jumping_leg(in1,tau,in3)
%DC_LOOP_JUMPING_LEG
%    DC = DC_LOOP_JUMPING_LEG(IN1,TAU,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    31-Oct-2017 15:28:29

dy = in1(4,:);
dC = dy;
