function E = energy_loop_jumping_leg(in1,in2)
%ENERGY_LOOP_JUMPING_LEG
%    E = ENERGY_LOOP_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    31-Oct-2017 15:28:29

I1 = in2(8,:);
I2 = in2(9,:);
Is = in2(13,:);
c1 = in2(3,:);
c2 = in2(4,:);
dth1 = in1(5,:);
dth2 = in1(6,:);
dy = in1(4,:);
g = in2(10,:);
kappa = in2(11,:);
l1 = in2(1,:);
l2 = in2(2,:);
m1 = in2(5,:);
m2 = in2(6,:);
mh = in2(7,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = sin(th1);
t9 = l1.*t2;
t14 = l2.*t2;
t3 = t9-t14;
t4 = cos(th1);
t11 = l1.*t4;
t5 = dy+dth1.*(t11+l2.*t4);
t6 = dth1.^2;
t7 = dy+c1.*dth1.*t4;
t8 = th1-th2;
t13 = c2.*t2;
t10 = t9-t13;
t12 = dy+dth1.*(t11+c2.*t4);
E = I1.*t6.*(1.0./2.0)+I2.*t6.*(1.0./2.0)+m1.*(t7.^2+c1.^2.*t2.^2.*t6).*(1.0./2.0)+Is.*dth2.^2.*(1.0./2.0)+kappa.*t8.^2.*(1.0./2.0)+m2.*(t6.*t10.^2+t12.^2).*(1.0./2.0)+mh.*(t3.^2.*t6+t5.^2).*(1.0./2.0)+g.*m1.*(y+c1.*t2)+g.*m2.*(t9+t13+y)+g.*mh.*(t9+t14+y);
