function rk = rk_jumping_leg(in1,tau,in3)
%RK_JUMPING_LEG
%    RK = RK_JUMPING_LEG(IN1,TAU,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    06-Nov-2017 23:36:07

l1 = in3(1,:);
l2 = in3(2,:);
th1 = in1(2,:);
y = in1(1,:);
t2 = cos(th1);
rk = [l2.*t2;y+l1.*sqrt(-1.0./l1.^2.*l2.^2.*t2.^2+1.0);0.0];
