function A = A_loop_jumping_leg(in1,in2)
%A_LOOP_JUMPING_LEG
%    A = A_LOOP_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    31-Oct-2017 15:28:29

I1 = in2(8);
I2 = in2(9);
Is = in2(13);
c1 = in2(3);
c2 = in2(4);
l1 = in2(1);
l2 = in2(2);
m1 = in2(5);
m2 = in2(6);
mh = in2(7);
th1 = in1(2);
t2 = cos(th1);
t3 = l1.*t2.*2.0;
t4 = c2.*t2.*2.0;
t5 = t3+t4;
t6 = m2.*t5.*(1.0./2.0);
t7 = l2.*t2.*2.0;
t8 = t3+t7;
t9 = mh.*t8.*(1.0./2.0);
t10 = c1.*m1.*t2;
t11 = t6+t9+t10;
t12 = sin(th1);
t17 = l1.*t12;
t13 = -t17+c2.*t12;
t15 = l1.*t2;
t14 = t15+c2.*t2;
t16 = t15+l2.*t2;
t18 = t17-l2.*t12;
t19 = c1.^2;
A = reshape([m1+m2+mh,t11,0.0,t11,I1+I2+m1.*(t2.^2.*t19.*2.0+t12.^2.*t19.*2.0).*(1.0./2.0)+m2.*(t13.^2.*2.0+t14.^2.*2.0).*(1.0./2.0)+mh.*(t16.^2.*2.0+t18.^2.*2.0).*(1.0./2.0),0.0,0.0,0.0,Is],[3,3]);
