function b = b_jumping_leg(in1,tau,Fy,in4)
%B_JUMPING_LEG
%    B = B_JUMPING_LEG(IN1,TAU,FY,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    02-Nov-2017 15:07:48

c1 = in4(3,:);
c2 = in4(4,:);
dth1 = in1(5,:);
dth2 = in1(6,:);
dy = in1(4,:);
g = in4(10,:);
kappa = in4(11,:);
l1 = in4(1,:);
l2 = in4(2,:);
m1 = in4(5,:);
m2 = in4(6,:);
mh = in4(7,:);
nu = in4(12,:);
th1 = in1(2,:);
th2 = in1(3,:);
t2 = sin(th1);
t3 = l1.*t2;
t4 = cos(th1);
t5 = c2.*t2;
t6 = c2.*t4;
t7 = t3+t5;
t8 = l1.*t4;
t9 = dth1.^2;
t10 = l2.*t2;
t11 = t3+t10;
t12 = t6+t8;
t13 = dth1.*t12;
t14 = dy+t13;
t15 = t6-t8;
t16 = l2.*t4;
t17 = t8+t16;
t18 = dth1.*t17;
t19 = dy+t18;
t20 = t3-t10;
t21 = c1.^2;
t22 = c1.*dth1.*t4;
t23 = dy+t22;
t24 = th1.*2.0;
t25 = t24-th2.*2.0;
b = [Fy-g.*m1-g.*m2-g.*mh+dth1.*(dth1.*m2.*t7+dth1.*mh.*t11+c1.*dth1.*m1.*t2);dth1.*(m1.*(c1.*t2.*t23.*2.0-dth1.*t2.*t4.*t21.*2.0).*(1.0./2.0)+m2.*(t7.*t14.*2.0+dth1.*t7.*t12.*2.0+dth1.*t15.*(t3-t5).*4.0).*(1.0./2.0)+mh.*(t11.*t19.*2.0+dth1.*t11.*t17.*2.0-dth1.*t20.*(t8-t16).*4.0).*(1.0./2.0))+mh.*(t9.*t20.*(t8-l2.*t4).*2.0-dth1.*t11.*t19.*2.0).*(1.0./2.0)-kappa.*t25.*(1.0./2.0)-nu.*(dth1-dth2)-m1.*(c1.*dth1.*t2.*t23.*2.0-t2.*t4.*t9.*t21.*2.0).*(1.0./2.0)-m2.*(dth1.*t7.*t14.*2.0+t9.*t15.*(t3-t5).*2.0).*(1.0./2.0)-g.*m2.*t12-g.*mh.*t17-c1.*g.*m1.*t4;tau+kappa.*t25.*(1.0./2.0)];
