function C = C_jumping_leg(in1,tau,in3)
%C_JUMPING_LEG
%    C = C_JUMPING_LEG(IN1,TAU,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    06-Nov-2017 23:36:07

y = in1(1,:);
C = y;
