function dC = dC_jumping_leg(in1,tau,in3)
%DC_JUMPING_LEG
%    DC = DC_JUMPING_LEG(IN1,TAU,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    02-Nov-2017 15:07:49

dy = in1(4,:);
dC = dy;
