function E = energy_jumping_leg(in1,in2)
%ENERGY_JUMPING_LEG
%    E = ENERGY_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    06-Nov-2017 23:36:05

I1 = in2(8,:);
I2 = in2(9,:);
Is = in2(13,:);
c1 = in2(3,:);
c2 = in2(4,:);
dth1 = in1(5,:);
dth2 = in1(6,:);
dy = in1(4,:);
g = in2(10,:);
kappa = in2(11,:);
l1 = in2(1,:);
l2 = in2(2,:);
m1 = in2(5,:);
m2 = in2(6,:);
mh = in2(7,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = 1.0./l1.^2;
t3 = l2.^2;
t4 = cos(th1);
t5 = t4.^2;
t11 = t2.*t3.*t5;
t6 = -t11+1.0;
t7 = sin(th1);
t8 = dth1.^2;
t9 = th1-th2;
t18 = c2.*t7;
t20 = l2.*t7;
t10 = t18-t20;
t12 = 1.0./sqrt(t6);
t13 = c2.*t4;
t14 = 1.0./l1;
t15 = sqrt(t6);
t16 = conj(t15);
t17 = 1.0./t16;
t19 = l1.*t16;
t21 = t3.*t4.*t7.*t12.*t14;
t22 = l2.*t4;
t23 = t3.*t4.*t7.*t14.*t17;
t24 = t7.^2;
E = I2.*t8.*(1.0./2.0)+Is.*dth2.^2.*(1.0./2.0)+kappa.*t9.^2.*(1.0./2.0)+m2.*(t8.*t10.^2+(dy+dth1.*(t13+t21)).*(dy+dth1.*(t13+t23))).*(1.0./2.0)+m1.*((dy+c1.*dth1.*t2.*t3.*t4.*t7.*t12).*(dy+c1.*dth1.*t2.*t3.*t4.*t7.*t17)+c1.^2.*t2.*t3.*t8.*t24).*(1.0./2.0)+g.*m1.*(y+c1.*t16)+mh.*(dy+dth1.*(t21+t22)).*(dy+dth1.*(t22+t23)).*(1.0./2.0)+g.*m2.*(t18+t19+y)+g.*mh.*(t19+t20+y)-(I1.*t2.*t3.*t8.*t24.*(1.0./2.0))./(t11-1.0);
