function E = energy_jumping_leg(in1,in2)
%ENERGY_JUMPING_LEG
%    E = ENERGY_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    28-Oct-2017 23:23:53

I1 = in2(7,:);
I2 = in2(8,:);
Is = in2(12,:);
c1 = in2(2,:);
c2 = in2(3,:);
dth1 = in1(5,:);
dth2 = in1(6,:);
dy = in1(4,:);
g = in2(9,:);
kappa = in2(10,:);
l = in2(1,:);
m1 = in2(4,:);
m2 = in2(5,:);
mh = in2(6,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = dth1.^2;
t7 = cos(th1);
t3 = dy+c1.*dth1.*t7;
t4 = sin(th1);
t5 = th1-th2;
t10 = c2.*t4;
t11 = l.*t4;
t6 = t10-t11;
t8 = dy+dth1.*(c2.*t7+l.*t7);
t9 = dy+dth1.*l.*t7.*2.0;
E = I1.*t2.*(1.0./2.0)+I2.*t2.*(1.0./2.0)+m1.*(t3.^2+c1.^2.*t2.*t4.^2).*(1.0./2.0)+Is.*dth2.^2.*(1.0./2.0)+kappa.*t5.^2.*(1.0./2.0)+mh.*t9.^2.*(1.0./2.0)+m2.*(t2.*t6.^2+t8.^2).*(1.0./2.0)+g.*m1.*(y+c1.*t4)+g.*mh.*(y+l.*t4.*2.0)+g.*m2.*(t10+t11+y);
