function keypoints = keypoints_loop_jumping_leg(in1,in2)
%KEYPOINTS_LOOP_JUMPING_LEG
%    KEYPOINTS = KEYPOINTS_LOOP_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    31-Oct-2017 15:28:29

l1 = in2(1,:);
l2 = in2(2,:);
th1 = in1(2,:);
y = in1(1,:);
t2 = cos(th1);
t3 = l1.*t2;
t4 = sin(th1);
t5 = l1.*t4;
keypoints = reshape([t3-l2.*t2,t5+y+l2.*t4,0.0,t3,t5+y,0.0,0.0,y,0.0],[3,3]);
